"""all models

Revision ID: 3e9451687109
Revises: 
Create Date: 2020-07-11 16:58:13.544003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9451687109'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mountain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Integer(), nullable=True),
    sa.Column('lon', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mountain_name'), 'mountain', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('refresh_token', sa.String(length=128), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('social_id', sa.Integer(), nullable=True),
    sa.Column('access_token', sa.String(length=128), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1280), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=1280), nullable=True),
    sa.Column('polyline', sa.String(length=1280), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_id')
    )
    op.create_table('user_mountain_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mountain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mountain_id'], ['mountain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'mountain_id')
    )
    op.create_table('activity_mountain_link',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('mountain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['mountain_id'], ['mountain.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'mountain_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_mountain_link')
    op.drop_table('user_mountain_link')
    op.drop_table('activity')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_mountain_name'), table_name='mountain')
    op.drop_table('mountain')
    # ### end Alembic commands ###
