"""added code column

Revision ID: 54ab353adaab
Revises: 1845150db670
Create Date: 2020-12-05 14:54:42.946179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54ab353adaab'
down_revision = '1845150db670'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('code', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'code')
    # ### end Alembic commands ###
