"""activities

Revision ID: 7c6e20ae1ef4
Revises: e1dc65927ddf
Create Date: 2020-06-11 19:42:28.573702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c6e20ae1ef4'
down_revision = 'e1dc65927ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1280), nullable=True),
    sa.Column('url', sa.String(length=1280), nullable=True),
    sa.Column('polyline', sa.String(length=1280), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_mountain_link',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mountain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mountain_id'], ['mountain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'mountain_id')
    )
    op.create_table('activity_mountain_link',
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('mountain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activity.id'], ),
    sa.ForeignKeyConstraint(['mountain_id'], ['mountain.id'], ),
    sa.PrimaryKeyConstraint('activity_id', 'mountain_id')
    )
    op.drop_table('link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('mountain_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['mountain_id'], ['mountain.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'mountain_id')
    )
    op.drop_table('activity_mountain_link')
    op.drop_table('user_mountain_link')
    op.drop_table('activity')
    # ### end Alembic commands ###
